
--TOTAL REVENUE BY MONTH
select [Monthday name],sum(revenue) AS TOTAL_REVENUE from [coffee shop] group by [Monthday name] order by sum(revenue)

--TRANSACTION BY DAYS OF THE WEEK
SELECT [weekday name], COUNT(TRANSACTION_ID) AS TOTAL_TRANSACTION FROM [coffee shop] GROUP BY [weekday name] ORDER BY COUNT(TRANSACTION_ID)

--TRANSACTION BY HOUR OF DAY
SELECT hour, COUNT(TRANSACTION_ID) AS TOTAL_TRANSACTION  FROM [coffee shop] GROUP BY HOUR ORDER BY COUNT(TRANSACTION_ID)

--TRANSACTION BY PRODUCT GATEGORY
SELECT product_category, COUNT(TRANSACTION_ID) AS TOTAL_TRANSACTION  FROM [coffee shop] GROUP BY product_category ORDER BY COUNT(TRANSACTION_ID) DESC

--TRANSACTION BY PRODUCT TYPE AND REVENUE
SELECT TOP 15 product_type, SUM(REVENUE) AS TOTAL_REVENUE, COUNT(TRANSACTION_ID) AS TOTAL_TRANSACTION FROM [coffee shop] GROUP BY product_type ORDER BY COUNT(TRANSACTION_ID) DESC






